### PR TITLE
Fix broken class matching on receive

### LINKED ISSUE #14: Does not work on macOS due to missing adapter address
(Backstory: I'm mostly developing on a RasPi 4 or a Bluefruit Sense, but I'm also trying to do comparisons against code running on Mac, as here)

Merely trying to import broadcastnet fails on the macOS platform even though adafruit_blinka_bleio supports mac, on the basis that the adapter never gets an address on mac (Python 3.7.9):
```
>>> import adafruit_ble_broadcastnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<....>/adafruit_ble_broadcastnet.py", line 67, in <module>
    _ble._adapter.address.address_bytes  # pylint: disable=protected-access
AttributeError: 'NoneType' object has no attribute 'address_bytes'
```
Relevant line in _bleio is 145 of https://github.com/adafruit/Adafruit_Blinka_bleio/blob/master/_bleio/adapter_.py: if it's not linux, an adapter just never gets an address.

I'm thinking this isn't actually necessary for bridge usage anyway? I'm going to try working around it and maybe submit a PR. I'm also open to being told it's foolish and underlying bleak support is insufficient on macos for other reasons.

### LINKED ISSUE #15: Cannot effectively scan with OSX, RasPi, or Feather Sense
This might be related to #11 but I can't say for sure - the symptoms don't totally overlap. The gist is, `ble.start_scan(adafruit_ble_broadcastnet.AdafruitSensorMeasurement)` will never return any advertisements to process, tested on Mac and RasPi. If, on the other hand, I `ble.start_scan()`, plenty of the relevant ads ARE getting scanned.

I'm running the following code on a Feather Sense:
``` python
import time
import microcontroller
import adafruit_ble_broadcastnet

from adafruit_ble import BLERadio
from adafruit_ble.advertising.adafruit import AdafruitColor
import random

ble = BLERadio()

print("This is BroadcastNet sensor:", adafruit_ble_broadcastnet.device_address)

while True:
   measurement = adafruit_ble_broadcastnet.AdafruitSensorMeasurement()
   measurement.temperature = (
      microcontroller.cpu.temperature  # pylint: disable=no-member
   )
   print(measurement)
   print(measurement.__repr__())
   #adafruit_ble_broadcastnet.broadcast(measurement, broadcast_time=3)
   ble.start_advertising(measurement)
   time.sleep(10)
   ble.stop_advertising()
```

On the RasPi, I'm using the following to scan:
``` python
import time
from adafruit_ble.advertising.standard import ManufacturerDataField
import adafruit_ble
import adafruit_ble_broadcastnet



ble = adafruit_ble.BLERadio()
bridge_address = adafruit_ble_broadcastnet.device_address
print("This is BroadcastNet bridge:", bridge_address)
print()

print("scanning")
print()
sequence_numbers = {}
# By providing Advertisement as well we include everything, not just specific advertisements.

# ====== Switch between these two lines for A/B testing ======
# for measurement in ble.start_scan(adafruit_ble_broadcastnet.AdafruitSensorMeasurement, interval=0.5):
for measurement in ble.start_scan(interval=0.5): 
    reversed_address = [measurement.address.address_bytes[i] for i in range(5, -1, -1)]
    sensor_address = "{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}".format(*reversed_address)
    if sensor_address == "f5bfcae0c159": ## On RasPi, the self-identified MAC address gets returned, so this looks sane.
        print(measurement.__repr__())

print("scan done")
```

On Mac, I'm using the following to implement the same test:
``` python
"""This example bridges from BLE to Adafruit IO on a Raspberry Pi, but without actually interacting with AIO at all"""
import time
from adafruit_ble.advertising.standard import ManufacturerDataField
import adafruit_ble
import adafruit_ble_broadcastnet

ble = adafruit_ble.BLERadio()
bridge_address = adafruit_ble_broadcastnet.device_address
print("This is BroadcastNet bridge:", bridge_address)
print()

print("scanning")
print()
sequence_numbers = {}

# ==== Again, switch between these two lines for testing ====
# for measurement in ble.start_scan(adafruit_ble_broadcastnet.AdafruitSensorMeasurement, interval=0.5):
for measurement in ble.start_scan(interval=0.5): 
    # Bleak on macOS doesn't deal in 6-byte MACs, so this obnoxious UUID is how things work.
    # Had to figure this out by waiting for an ad with the right complete_name, then checking this value.
    # Don't want to filter by name alone as some ads might be surfaced without complete_name.
    if measurement.address.string == "3A8F6F02-DA05-41C9-83D4-835F626674DC":
        print(measurement.__repr__())
print("scan done")
```

The result of this test:
```
# Ad as printed by the Feather:
Advertisement(data=b"\x0a\xff\x22\x08\x06\x04\x0a\x00\x00\xae\x41")

# Ad as it comes through on Mac in a generic scan:
Advertisement(data=b"\x0a\xff\x22\x08\x06\x04\x0a\x00\x00\xae\x41\x0e\x09\x43\x49\x52\x43\x55\x49\x54\x50\x59\x63\x31\x35\x39")

# Ad as it comes through on the Pi in a generic scan (these two ads repeat in alternation - I guess the Pi reports the 
# add, then reports again if a scan_response comes through, where Mac waits to avoid duplication.)
Advertisement(data=b"\x0a\xff\x22\x08\x06\x04\x0a\x00\x00\xae\x41")
Advertisement(data=b"\x02\x0a\x00\x0e\x09\x43\x49\x52\x43\x55\x49\x54\x50\x59\x63\x31\x35\x39")

# As ads come through on the Feather Sense in a generic scan, which looks identical to the Pi. Note that the reported temperature changed, because this is a new test at a different time (0xAE vs 0xB6).
Advertisement(data=b"\x0a\xff\x22\x08\x06\x04\x0a\x00\x00\xb6\x41")
Advertisement(data=b"\x02\x0a\x00\x0e\x09\x43\x49\x52\x43\x55\x49\x54\x50\x59\x63\x31\x35\x39")
```
I'm not quite sure what to make of this, but it looks like the check of `match_prefixes` is failing for some non-obvious reason, given that the ad data payload looks pretty matchy to me in the Mac case, and in at least the shorter Pi case.

EDIT: I just tested with a second Feather Sense running the RasPi version of the gateway code, and got matching results to the Pi. I noticed at the same time that the manufacturer data appears to be included in the first advertisement but not the second, which I guess is normal - the scan_response doesn't duplicate the original manufacturer data payload.

### PR DESCRIPTION
**Pull request by alexwhittemore**
Restructured match_prefixes to correctly match sequence number field
Added insurance that sequence number comes first to do so
Also caught the (macOS) case where adapter has no address (WIP)
Fixes #15

The macOS address bit fixes #14 but maybe ought to actually implement @dhalbert's suggestion of hashing the UUID-style address rather than just smashing zeros into it.

### CODE REVIEW

**Comment by alexwhittemore** [comment]
Well that was an adventure.

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by tannewt** [comment]
Looks like `move_to_end` isn't available on CircuitPython (#18). What board did you test this on?

**Comment by alexwhittemore** [comment]
Oh damn - I was SENDING with a bluefruit sense, BUT I was receiving (where this code is relevant) on a RasPi.

Edit: No, that doesn't seem right, because the whole point is to ensure proper order when SENDING. I'll keep looking and see what the idea was.

**Comment by alexwhittemore** [comment]
Now that I've thought about this a bit more - I recall I TRIED to ensure byte order on the sending side by ensuring that the sequence number field was the first set, but that didn't work for some reason I don't recall - something like, in one spot, if the sequence number was already set, it wouldn't get updated.

I'm thinking it's possible that if this bug IS only on the sending side, I might have switched it up and LISTENED with the feather, and advertised with the Pi so I could interactively debug it.

**Comment by alexwhittemore** [comment]
I DID just verify that sending fails on a feather sense. I think I was actually debugging this before on my mac, not even on raspberry pi. 

Anywho, I'm really not sure what to do about it - the sequence number field has to be at the start, or else prefix matching will fail. Or the prefix could be relaxed, but I think that means other advertisements will potentially get flagged as `AdafruitSensorMeasurement`s?

**Comment by tannewt** [comment]
Could you sort it with code instead of a function call?

**Comment by alexwhittemore** [comment]
Actually, it looks like OrderedDict is implemented in pure python, so I suppose I can just monkey-patch in the OEM method right here. I'll give it a test.

**Comment by alexwhittemore** [comment]
Hmm. I'm not sure what's going on with CircuitPython's OrderedDict (can't search for it on github because fork, so I have no clue what it looks like) but in any event, 1) it looks like CP's python implementation doesn't actually support monkeypatching, which I guess is probably a memory thing? 2) OrderedDict is missing `self.__map` and `self.__root` which are required for ordering in the first place. It's a little as if `OrderedDict` throws away all the stuff that makes an `OrderedDict` ordered? 

For background, this is futzing around on a feather REPL:
```
>>> foo = OrderedDict({1:"first", 8:"eighth"})
>>> foo.__root
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OrderedDict' object has no attribute '__root'
>>> foo.__map
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OrderedDict' object has no attribute '__map'
>>> def printfoo(self):
...     print(self)
... 
>>> OrderedDict.printfoo = printfoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'type' object cannot assign attribute 'printfoo'
```

When I tried to add the following to broadcastnet:
```python
def move_to_end(self, key, last=True):
    '''Move an existing element to the end (or beginning if last is false).
    Raise KeyError if the element does not exist.
    '''
    link = self.__map[key]
    link_prev = link.prev
    link_next = link.next
    soft_link = link_next.prev
    link_prev.next = link_next
    link_next.prev = link_prev
    root = self.__root
    if last:
        last = root.prev
        link.prev = last
        link.next = root
        root.prev = soft_link
        last.next = link
    else:
        first = root.next
        link.prev = root
        link.next = first
        first.prev = soft_link
        root.next = link
```
and
```python
    def __bytes__(self):
        """The raw packet bytes."""
        # Must reorder the ManufacturerData contents so the sequence number field is always first.
        # Necessary to ensure that match_prefixes works right to reconstruct on the receiver.
        move_to_end(self.data_dict[255].data, 3, last=False)
        return super().__bytes__()
```
(so not monkey patching, just private access) I get 
```
code.py output:
This is BroadcastNet sensor: db966a80fab2
<AdafruitSensorMeasurement temperature=23.0 battery_voltage=4176 >
Traceback (most recent call last):
  File "code.py", line 36, in <module>
  File "/lib/adafruit_ble_broadcastnet.py", line 37, in broadcast
  File "adafruit_ble/__init__.py", line 183, in start_advertising
  File "/lib/adafruit_ble_broadcastnet.py", line 196, in __bytes__
  File "/lib/adafruit_ble_broadcastnet.py", line 68, in move_to_end
AttributeError: 'OrderedDict' object has no attribute '__map'
```

**Comment by tannewt** [comment]
I think you've found that OrderedDict is implemented in a different way in MicroPython. MicroPython isn't based on CPython's code and is also licensed differently as well. (So be careful mixing code.)

The easier approach would be to sort the keys before encoding them in bytes. (IIRC the sequence number is the lowest of them.)

**Comment by alexwhittemore** [comment]
Fair point about mixed licensing.

My point about sorting keys at all is that it seems the only practical way to sort them up at the library level is to tightly control the order in which they're added, but ensuring the sequence number is always added first by, for instance, setting it to Null or something in the constructor breaks other aspects of the library design (I forget exactly how).

**Comment by tannewt** [comment]
I don't understand why you need the dictionary ordered when all you are about is that they are encoded in order. (I think you'd change: https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/master/adafruit_ble/advertising/__init__.py#L57-L72 to sort the keys first.)

**Comment by alexwhittemore** [comment]
Oh - well, because that code isn't in this library. I guess you're suggesting monkey-patch in a modified adafruit_ble.advertising.encode_data() to serve the purposes of BroadcastNet? Given my experience before trying to monkey patch in circuitpython - is that even possible? If it is, it would break the case where we load BroadcastNet but then try to transmit a non-broadcastnet advertisement (I think) - unless I'm missing your idea.

**Comment by tannewt** [comment]
No, I'm suggesting you change the BLE library so it consistently orders keys. Much simpler than monkey patching.

**Pull request merged**
